[versions]
spring-context = "6.1.3"
junit-jupiter = "5.10.0"
lombok = "1.18.30"
slf4j = "2.0.11"
google-findbugs= "3.0.2"
jackson-annotations = "2.16.1"

[libraries]
spring-context = { module = "org.springframework:spring-context", version.ref = "spring-context" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
slf4j= {module ="org.slf4j:slf4j-api", version.ref = "slf4j"}
google-findbugs = { module = "com.google.code.findbugs:jsr305", version.ref = "google-findbugs" }
jackson-annotations = {module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson-annotations"}

# For tests
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }

