/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.mrsaraira.stateful.scheduler;

import org.junit.jupiter.api.Test;


class LibraryTest {

    @Test
    void someLibraryMethodReturnsTrue() {
    }

}
